sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "io.js"
  - "4"
  - "5"
  - "6"
env:
  - TEST_SUITE=coverage
  - TEST_SUITE=standard
  - TEST_SUITE=unit
script: "npm run-script $TEST_SUITE"
